# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e96f19f23dc8bec7d03551db5bb3b07bea01e0a14d48058ac6e3b7686afcf621b437e1fc2fc03427552679da65d7d6c3fad07b56964ebd7d2642a2f0e32d6e

test:
  secret_key_base: 9be675ae0077aeec07c3901b1ef1f84eecf609cd93db4ab9fa3c2c004fada3d428bfa9854a206d10af64f5e9f72a66170589909bfdac3acd86360a81af4517f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
